### ISSUE TITLE
No full screen

### ISSUE THREAD

**Issue by dekkerj1** [SanderKlootwijk/ubuntu-nednieuws#1]
On BQM10 Nednews does not open in full screen mode.

**Comment by SanderKlootwijk** [comment]
Thank you for reporting this bug. Do you mean that full screen video doesn't work for example? Or is the issue different?

**Comment by SanderKlootwijk** [comment]
I assume this issue is fixed in the latest release of NedNieuws (2.1, available in the OpenStore), so I'll close this issue for now. Please re-open if necessary.
